apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: sergeyooo/random-number-generator:latest
          env:
            - name: MONGO_HOST
              value: "db-service"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: "test_k8s"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
