apiVersion: batch/v1
kind: Job
metadata:
  name: docker-build-job
spec:
  template:
    spec:
      containers:
        - name: docker-build
          image: docker:latest
          command: ["docker"]
          args:
            - "build"
            - "-t"
            - "random-number-generator:latest"
            - "."
      restartPolicy: Never
